### PR TITLE
alterac/classic: add timers

### PR DESCRIPTION
**Pull request by venuatu**

### CODE REVIEW

**Comment by venuatu** [comment]
This is for classic only, i assume the timers come from somewhere else in retail.
It's detecting all bases and mines atm
There seems to be a bug with snowfall gy cap having a wrong icon
This should work with all locales once people contribute some localizations
Hit me up if you see anything bad, i never code in luaa

**Comment by MysticalOS** [comment]
We're hoping it can be done without locals, using the widget api, IF it works in classic as well. that's something have to run some debug on. I'll try to find out definitively if widgets can be used tomorrow, if not I'll definitely merge this in for classic

**Comment by wallrik** [comment]
Is the start timer needed? Isn't it handled by the START_TIMER event in PvPGeneral.lua already? Seems to work fine for me.

**Comment by MysticalOS** [comment]
It's not needed no, if I had to guess it probably didn't work at time they did their code, so they added localized version of it, remember START_TIMER was throwing a lua error til i fixed it yesterday was it?

Either way, if Paws finishes workon widget stuff for AV, we souldn't need to rely on any localized solutions. while this PR works, it's probably worst way to go about supporting it since it requires much translation. None the less, if paws takes TOO long to finish correct way, I may add this as a temporary hold over so mod isn't useless while we wait

**Comment by venuatu** [comment]
Neither dbm pvp or capping battleground timers worked for me or the people I play with on classic oceanic realms.
I had a separate fix for the faction check before this PR and there were no errors coming from this addon at that point.
Is this issue localised just to oceanic realms or something?

**Comment by jazzl1984** [comment]
yeh, there is no graveyard/tower timer bar in zhcn server either. Actually, when i play 1.12 in nost, CN client dbm pvp config window only show little settings already. I think this issue was caused by localization

**Comment by venuatu** [comment]
I did some more digging and we can pull the localised names and textures with area poi apis.
C_AreaPoiInfo.GetAreaPOITimeLeft doesn't work though, always comes back with nil and the new version isn't implemented in classic.

So it seems like the best plan would be to snapshot the pois on AREA_POIS_UPDATED and watch for changes.
It seems like this is maybe 70% implemented, though in my classic client and inside AV the:
- AREA_POIS_UPDATED widget parameter is always nil, therefore none of the if statements run
- it seems like in AV each poi would need three states instead of the two in the widgetID 1671 code, as in: untouched, capping and destroyed, rather than horde or ally capped

**So, should I work on this or is for paws?**

In any case I worked out the below textureIndex values:
- 0 control mine npc
- 1 control mine ally
- 2 control mine horde
- 3 capping gy ally
- 4 ?
- 5 destroyed tower (ally & horde)
- 6 ?
- 7 ?
- 8 capping tower ally
- 9 control tower horde
- 10 control tower ally
- 11 capping tower horde
- 12 control gy horde
- 13 capping gy horde
- 14 control gy ally

And you can use the below to print out the current values:
```
/script for i, x in pairs(C_AreaPoiInfo.GetAreaPOIForMap(1459)) do local a = C_AreaPoiInfo.GetAreaPOIInfo(1459, x); print(tostring(x)..':'..tostring(a.name)..'|'..tostring(a.atlasName or a.textureIndex)) end
1459 comes from C_Map.GetBestMapForUnit("player")
```
for:
```
19:03 1358:Coldtooth Mine|2
19:03 1355:Dun Baldar South Bunker|5
19:03 1352:Dun Baldar North Bunker|5
19:03 1351:Frostwolf Relief Hut|12
19:03 1255:East Frostwolf Tower|9
19:03 1099:Irondeep Mine|2
19:03 1527:West Frostwolf Tower|9
19:03 1374:Iceblood Graveyard|14
19:03 1208:Stormpike Graveyard|14
19:03 1210:Frostwolf Graveyard|12
19:03 1377:Iceblood Tower|5
19:03 1405:Tower Point|5
19:03 1395:Stormpike Aid Station|12
19:03 1392:Stonehearth Graveyard|12
19:03 1389:Stonehearth Bunker|5
19:03 1386:Snowfall Graveyard|14
19:03 1380:Icewing Bunker|5
```

**Comment by MysticalOS** [comment]
Yes that's exactly what Paws is working on, but I'll pass that on in case it helps speed that up :)

**Comment by MysticalOS** [comment]
I'm told paws doesn't have time to review this right now, so if you've made progress I'll go ahead and look at it/merge it in to get an update out sooner. If you can get mods working using the POI api, we'll be golden.

**Comment by venuatu** [comment]
I should be able to knock it out later today.
Just one question: Why is the name attribute used on area pois ([as in arathi](https://github.com/DeadlyBossMods/DBM-PvP/blob/master/DBM-PvP/Battlegrounds/Arathi.lua#L29)) rather than the poi id? it seems to me like the id would be the same in different locales whereas the name could be different.

**Comment by MysticalOS** [comment]
I imagine at API level, it isn't localized, it returns english strings.

Same as UnitFaction apis always returning "Alliance" or "Horde" regardless of language.

To answer your question though I have no idea. sadly I don't know anythinga bout new apis really, I didn't have time to work on PVP mods so @Developaws did all the work. I just accept whatever works best for all users.

**Comment by venuatu** [comment]
This is working now with the areapoi apis.
I've tested it in classic AV and retail korrak, noone seemed to be queuing retail AV, so i couldn't get the right textures for that, maybe I can get those once the korrak event is over.
I just implemented it in the alterac file, so it didn't mess with other bgs, it can be pulled into general if that's what people want.

**Comment by MysticalOS** [comment]
Only change I'd like to see is not creating a whole bunch fo mod:NewTimer

Try to create one like other mods do, and reuse it. you could make timer text %s and just change that with the arg and :updateicon call, you can see how other mods do it. it's pretty dirty to just create like 24 different timer objects.

as forstopping mod, you shouldn't even need to make a timers table, just call mod:Stop() in bgzone = false spot.

also feel free to join DBM discord if you want to chat more. https://discord.gg/deadlybossmods

**Comment by venuatu** [comment]
I'll take a look at that tomorrow, its getting late over here.
I just assumed when i want a timer for every in progress tower/gy that would mean a NewTimer for each one.

**Comment by MysticalOS** [comment]
Ok then I'll merge it now then make the changes, cause I want to work on getting this out to people.

**Pull request merged**
